build: General build improvements
Primarily merged from my VidTu/Ksyxis and VidTu/HCsCR projects.
Quick rundown of all the changes:
- CI: Automatically add 'type:bot' labels for bot PRs.
- CI: Separate legacy builds into a separate action that can be ran on-demand.
- CI: Non-legacy builds now time out after 60 mins. (legacy after 90 still)
- CI: Non-main-branch (or legacy) builds no longer write to Gradle cache.
- CI: Removed unused property IAS_LEGACY. (now in separate action)
- CI: Prepare for the renovate bot.
- Build: Added Kyori Blossom plugin (unused now, for future use).
- Build: Added Intellij IDEA Ext plugin. (should solve some issues with IDEA)
- Build: Removed references to (now deleted) "quilt.mod.json" file.
- Build: Switch to centralized Stonecutter 0.9 properties format for versions.
  - That means that lots of separate "gradle.properties" files are gone.
  - Properties moved from separate files to "stonecutter.properties.json":
    1. "sc.fabric-api" -> "<version>.fabric.api" in JSON.
    2. "sc.modmenu" -> "<version>.fabric.modmenu" in JSON.
    3. "sc.modmenu.compile-only" is now done by prefixing ModMenu with '$'.
       - Kinda magical, I know.
       - Only supported for Mojmap. (26.1+)
    4. "sc.minecraft-dependency" -> "<version>.fabric.minecraft" in JSON.
       - Was only supported for Fabric, moved there for that reason.
       - Only supported for Mojmap. (26.1+)
    5. "sc.minecraft-requirement" -> "<version>.fabric.constraints" in JSON.
       - Now only supported for Fabric. (no more support for Forge/NeoForge)
       - Only supported for Mojmap. (26.1+)
    6. "sc.forge" -> "version.forge.loader" in JSON.
    7. "sc.neoforge" -> "version.neoforge.loader" in JSON.
    8. "sc.platform-requirement" -> "version.<loader>.constraints" in JSON.
       - Different keys for Forge/NeoForge.
       - No longer read for Fabric.
  - Ignored versions are now stored in "dev/versions/ignored.txt".
- Build: Remove unneeded statement that disabled Mixin AP on Fabric.
- Build: Versions are now stored in "dev/versions" instead
  of being hardcoded into "settings.gradle.kts" script.
  - Beta versions: "dev/versions/versions_beta.txt"
    - No difference from "Active" for now.
    - Future difference: Won't be uploaded to Modrinth/CurseForge/etc.
  - Active versions: "dev/versions/versions_active.txt"
  - Legacy versions: "dev/versions/versions_legacy.txt"
    - Not compiled unless legacy mode is on.
  - Ignored versions (aforementioned above) are always ignored.
- Build: Cleaned the Architectury repositories. (we no longer use it)
- Build: Now reporting the mode of execution. (normal/legacy/onlyId)
  - No longer reporting loudly on which versions are excluded.
- Dev: More Minecraft debug properties (see wiki) are now used.
- Dev: Scripts are no longer running in debug/xtrace/echo-on mode.
- Dev: Scripts are now more talkative. Gradle processes are reported exit-code.
- Dev: Scripts that require an argument now check for that argument.
- Dev: Compile-one script now requires specifying mode: "normal"/"legacy".
  - Previously was done with "--legacy" flag.
- Dev: Launch-all testing script now pauses if exit-code is not 0.
  - Can abort or continue.
- Meta: Expanded "IAS" into "In-Game Account Switcher" in some errors.
- Meta: Add some important contributor names into Contributors field.
  - I plan to eventually add everyone there (chronologically), hit me up.
- Bumped loaders/dependencies.
- Some other fixes, some minor.

The next big change should be the addition of the upload script,
which should be also adapted from my other projects to work with
multiple versions, CurseForge/Modrinth/GitHub/Discord/etc.

diff --git a/compileall b/compileall
--- a/compileall
+++ b/compileall
@@ -19,15 +19,24 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
 
-# Check legacy state.
-for arg in "$@"; do [ "${arg}" = '--legacy' ] && IAS_LEGACY=true; done
-if [ "${IAS_LEGACY:-}" = "true" ]; then
-    # Build with legacy.
-    ./gradlew -Dru.vidtu.ias.legacy=true assemble
+# Check args.
+if [ "${1:-}" = 'legacy' ]; then
+    # Build in legacy mode.
+    echo 'SCRIPT: Building in legacy mode...'
+    ./gradlew -Dru.vidtu.ias.legacy=true assemble && true
+    echo "SCRIPT: Build in legacy mode exited with code ${?}."
+elif [ "${1:-}" = 'normal' ]; then
+    # Build in normal mode.
+    echo 'SCRIPT: Building in normal mode...'
+    ./gradlew assemble && true
+    echo "SCRIPT: Build in normal mode exited with code ${?}."
 else
-    # Build without legacy.
-    ./gradlew assemble
+    # Fail.
+    echo 'SCRIPT: You must specify the mode of execution.'
+    echo 'Normal (Beta/Active): ./compileall normal'
+    echo 'Legacy (Beta/Active/Legacy): ./compileall legacy'
+    exit 2
 fi
diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -19,8 +19,17 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
+
+# Check args.
+if [ "${#}" -eq 0 ]; then
+    echo 'SCRIPT: You must specify the version to launch.'
+    echo 'Example: ./launch 1.20.1-fabric'
+    exit 2
+fi
 
 # Launch.
-./gradlew "-Dru.vidtu.ias.only=${1}" "${1}:runClient"
+echo "SCRIPT: Launching '${1}'..."
+./gradlew "-Dru.vidtu.ias.only=${1}" "${1}:runClient" && true
+echo "SCRIPT: Launch for '${1}' exited with code ${?}."
diff --git a/launchall b/launchall
--- a/launchall
+++ b/launchall
@@ -19,14 +19,20 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
 
 # Iterate.
-for folder in versions/*; do
+echo 'SCRIPT: Launching all versions...'
+for LAUNCH_FOLDER in versions/*; do
     # Extract the version (only the folder name) from the full relative path.
-    version=$(basename -- "${folder}")
+    LAUNCH_VERSION=$(basename -- "${LAUNCH_FOLDER}")
 
-    # Launch, unless ".ignored" exists.
-    [ -f "${folder}/.ignored" ] || ./gradlew "-Dru.vidtu.ias.only=${version}" "${version}:runClient"
+    # Launch.
+    echo "SCRIPT: Launching '${LAUNCH_VERSION}'..."
+    ./gradlew "-Dru.vidtu.ias.only=${LAUNCH_VERSION}" "${LAUNCH_VERSION}:runClient" && true
+    LAUNCH_EXIT="${?}"
+    echo "SCRIPT: Launch for '${LAUNCH_VERSION}' exited with code ${LAUNCH_EXIT}."
+    [ "${LAUNCH_EXIT}" -ne 0 ] && echo 'SCRIPT: Non-zero exit code. Press Enter to continue, terminate (CTRL+C) to cancel.' && read -r _
 done
+echo 'SCRIPT: Done launching all versions.'
diff --git a/reset b/reset
--- a/reset
+++ b/reset
@@ -19,8 +19,10 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
 
 # Reset.
-./gradlew "Reset active project"
+echo 'SCRIPT: Resetting active project...'
+./gradlew "Reset active project" && true
+echo "SCRIPT: Resetting active project exited with code ${?}."
diff --git a/switch b/switch
--- a/switch
+++ b/switch
@@ -19,8 +19,17 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>
 
-# Fail on error, fail on unbound variable, verbose mode, xtrace mode, pipefail mode.
-set -euvxo pipefail
+# Fail on error, fail on unbound variable, pipefail mode.
+set -euo pipefail
+
+# Check args.
+if [ "${#}" -eq 0 ]; then
+    echo 'SCRIPT: You must specify the version to switch.'
+    echo 'Example: ./switch 1.20.1-fabric'
+    exit 2
+fi
 
 # Switch.
-./gradlew "Set active project to ${1}"
+echo "SCRIPT: Switching to '${1}'..."
+./gradlew "Set active project to ${1}" && true
+echo "SCRIPT: Switching to '${1}' exited with code ${?}."
