dev: Helper script improvements [ci skip]
- Don't require bash. (plain sh is ok now)
- Add cmd.exe scripts for Windows.
- Make UNIX scripts have executable flag.
- More verbosity.
- Skip launching ignored folders in launchall.

diff --git a/reset b/reset
--- a/reset
+++ b/reset
@@ -1,4 +1,5 @@
-#!/usr/bin/env bash
+#!/bin/sh
+#
 # In-Game Account Switcher is a third-party mod for Minecraft Java Edition that
 # allows you to change your logged in account in-game, without restarting it.
 #
@@ -18,4 +19,8 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>
 
+# Fail on error, fail on unbound variable, verbose mode, xtrace mode.
+set -euvx
+
+# Reset.
 ./gradlew "Reset active project"
